name: Update Data

on:
  schedule: # Run every day at fixed time
    - cron: "13 16 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:          
          ssh-key: ${{ secrets.DATA_UPDATE_PRIVATE_KEY }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: requirements.txt
          auto-activate-base: false
      - name: Script
        run: |
          mkdir -p ./cache
          ./update_data.sh
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update CSV data
          title: Update CSV
          branch: auto/update-data
          labels: bot
