name: Update Data

on: 
 schedule:
    # Run every day at fixed time
    - cron: "13 16 * * *"
 push:
    branches:
    - main

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: requirements.txt
          auto-activate-base: false
      - name: Script
        run: |
          mkdir -p ./cache
          ./update_data.sh
          git status
